[package]
name = "tagmaster"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["tokio", "image", "advanced"]}
iced_aw = { version = "0.12", features = ["card"] }
rfd = "0.15.4"
webbrowser = "1.0.6"
box = {path = "box-api", package = "openapi"}

[profile.dev.package."*"]
opt-level = 3

