[target.aarch64-apple-darwin]
# Install libssl-dev:arm64, see <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH"
]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"
env.passthrough = ["AWS_LC_SYS_CFLAGS_aarch64_apple_darwin=-stdlib=libc++"]